### ISSUE TITLE
Getting parse issue for web.config file

### ISSUE THREAD

**Issue by Rakesh201180** [IdentityModel/IdentityModel#230]
Getting below error when calling API from application. both have separate web.config file, below configuration present in Application config file. 

ID8030: The value of the 'type' property could not be parsed. Verify that the type attribute of `<issuerNameRegistry type="Thinktecture.IdentityModel.Tokens.MetadataBasedIssuerNameRegistry, Thinktecture.IdentityModel"><trustedIssuerMetadata issuerName="urn:federation:xyz:stage" metadataAddress="https://federation-sts-stage.xyz.com/FederationMetadata/2007-06/FederationMetadata.xml"></trustedIssuerMetadata></issuerNameRegistry>` element is correct.

please suggest

**Comment by Rakesh201180** [comment]
` <system.identityModel>
    <identityConfiguration saveBootstrapContext="false">
      <audienceUris>
        <add value="https://testdev.container.xyz.com" />

      </audienceUris>
      <certificateValidation certificateValidationMode="None">
      </certificateValidation>
      <issuerNameRegistry type="Thinktecture.IdentityModel.Tokens.MetadataBasedIssuerNameRegistry, Thinktecture.IdentityModel">
        <trustedIssuerMetadata issuerName="urn:federation:xyz:stage" metadataAddress="https://federation-sts-stage.xyz.com/FederationMetadata/2007-06/FederationMetadata.xml">
        </trustedIssuerMetadata>
      </issuerNameRegistry>
    </identityConfiguration>
  </system.identityModel>`

**Comment by leastprivilege** [comment]
Sorry - this sounds like you are talking about Microsofts `System.IdentityModel' library - I can't help you with that.
