### ISSUE TITLE
CIBA constants

### ISSUE THREAD

**Issue by brockallen** [IdentityModel/IdentityModel#422]
Placeholder for CIBA constants needed (some might already be defined, just adding as I read the spec). 

grant type: `urn:openid:params:grant-type:ciba`

OpenID Provider Metadata
`backchannel_token_delivery_modes_supported`: array of: `poll`, `ping`, and/or `push`
`backchannel_authentication_endpoint`: URL
`backchannel_authentication_request_signing_alg_values_supported`: array JWS algs
`backchannel_user_code_parameter_supported`: bool

Backchannel Authentication Endpoint Request Params:
scope
client_notification_token
acr_values
login_hint_token
id_token_hint
login_hint
binding_message
user_code
requested_expiry

Plus we need a new HttpClient extension method for Backchannel Login Request and for polling the Token Endpoint.

**Comment by leastprivilege** [comment]
above constants are done. Please add more below if needed.

**Comment by brockallen** [comment]
Still needed:
Token Request Params:
"auth_req_id"

Backchannel Authentication Endpoint Request Params:
resource

Token request using ciba grant
resource

Backchannel Login Endpoint Errors (do those go in IDM or in IS constants?):

InvalidRequestObject = "invalid_request_object"
            public const string InvalidRequest = "invalid_request";
            public const string InvalidScope = "invalid_scope";
            public const string ExpiredLoginHintToken = "expired_login_hint_token";
            public const string UnknownUserId = "unknown_user_id";
            public const string UnauthorizedClient = "unauthorized_client";
            public const string MissingUserCode = "missing_user_code";
            public const string InvalidUserCode = "invalid_user_code";
            public const string InvalidBindingMessage = "invalid_binding_message";
            public const string InvalidClient = "invalid_client";
            public const string AccessDenied = "access_denied";
            public const string InvalidTarget = "invalid_target";

**Comment by leastprivilege** [comment]
needs discussion

**Comment by leastprivilege** [comment]
done and updated package ready for testing.

**Comment by leastprivilege** [comment]
todo: make sure various HTTP status codes are handled correctly for BC authN endpoint.

**Comment by brockallen** [comment]
> Token Request Params:
> "auth_req_id"

Did this one make it in? I don't see it on `OidcConstants.TokenRequest`.

**Comment by brockallen** [comment]
> Did this one make it in? I don't see it on OidcConstants.TokenRequest.

Ok, I see it in there... *uckin* visual studio.

Ok, IS now updated. I think we got them all.

**Comment by leastprivilege** [comment]
Please try the extension methods

**Comment by brockallen** [comment]
DiscoveryDocumentResponse needs BackchannelAuthenticationEndpoint

and backchannel_token_delivery_modes_supported, and backchannel_user_code_parameter_supported, i guess?

**Comment by brockallen** [comment]
BackchannelAuthenticationRequest.RequestedExpiry should be nullable (it's optional)

**Comment by brockallen** [comment]
When using the request object, I get this exception calling `RequestBackchannelAuthenticationAsync`:

```
Unhandled exception. System.ArgumentException: Parameter is required (Parameter 'scope')
   at IdentityModel.Client.Parameters.AddRequired(String key, String value, Boolean allowDuplicates, Boolean allowEmptyValue)
   at IdentityModel.Client.HttpClientBackchannelAuthenticationExtensions.RequestBackchannelAuthenticationAsync(HttpMessageInvoker client, BackchannelAuthenticationRequest request, CancellationToken cancellationToken)
   at ConsoleCibaClient.Program.RequestBackchannelLoginAsync() in C:\ballen\work\Duende\github\IdentityServer\clients\src\ConsoleCibaClient\Program.cs:line 75
   at ConsoleCibaClient.Program.Main() in C:\ballen\work\Duende\github\IdentityServer\clients\src\ConsoleCibaClient\Program.cs:line 25
   at ConsoleCibaClient.Program.<Main>()
```

Along these lines, I guess if the request object is present, then none of the other params should be added. Maybe that's an easy way to implement the conditional logic when building the params.

**Comment by leastprivilege** [comment]
updates and pushed.
