### ISSUE TITLE
5.1.1 broke binary compatability

### ISSUE THREAD

**Issue by royvandertuuk** [IdentityModel/IdentityModel#430]
Commit 1db21e2677de6896bc11227c70b927c502e20898 broke the binary compatibility.
An optional parameter was added to DiscoveryEndpoint.ParseUrl, this does not break source compatibility but it does break binary compatibility.

This causes issues because we are using the IdentityModel package in our own packages. This prevents us from updating to the latest IdentityModel without recompiling our own packages.

My suggestion is to restore the DiscoveryEndpoint.ParseUrl without the path parameter and create an overload that accepts a path parameter.

**Comment by leastprivilege** [comment]
I am sorry. Please recompile your packages if you need this update.
