### ISSUE TITLE
ClientCredentialsTokenRequest uses GET method by default, but should be POST

### ISSUE THREAD

**Issue by DanielSlessarevTR** [IdentityModel/IdentityModel#432]
https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/TokenRequest.cs#L27

`ClientCredentialsTokenRequest` inherits the default value for the `Method` field from `HttpRequestMessage`
That default value is GET.
However, the vast majority of oauth implementations for the /token endpoint (client credentials) use POST method.
https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
https://auth0.com/docs/api/authentication#client-credentials-flow
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#get-a-token

I believe, the default value for `Method` in `ClientCredentialsTokenRequest` should be POST.

**Comment by leastprivilege** [comment]
I does use POST - have you ever tried it?

https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Extensions/HttpClientTokenRequestExtensions.cs#L218
