### ISSUE TITLE
Why is `StringComparisonAuthorityValidationStrategy` the default?

### ISSUE THREAD

**Issue by aristotelos** [IdentityModel/IdentityModel#436]
Hi, I have a question regarding the authority validation. There are two policies: `AuthorityUrlValidationStrategy` and `StringComparisonAuthorityValidationStrategy`. The current default validation policy is `StringComparisonAuthorityValidationStrategy`. This gives me issues when my host name differs in case, e.g. I have configured the endpoint as `MYEXAMPLEHOST.com` and the `.well-known/openid-configuration` returns `myexamplehost.com`, or vice versa. Actually this is incorrect behavior of the IdentityModel client, because host names are always case insensitive. See [this StackOverflow post](https://stackoverflow.com/questions/15641694/are-uris-case-insensitive/26196170#26196170) and its referenced RFCs.

Why is the `AuthorityUrlValidationStrategy` not the default? It has support of case insensitivity for the host name, and case sensitivity for the path, which is how it should be (so `MYEXAMPLEHOST.com` and `myexamplehost.com` are identical, but `myexamplehost.com/path` and `myexamplehost.com/PATH` are not). Using string comparison as the default leads to behavior that is contrary to the URL specifications.

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-connect-discovery-1_0.html

> 4.3.  OpenID Provider Configuration Validation
The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

I guess this why this was chosen as the default. It's a long time ago..

**Comment by aristotelos** [comment]
I would say with that text someone can argue for URL equality as well as
for string equality - or actually better. The OpenID Connect specification
does not tell us explicitly to ignore the equality rules for URLs, does it?

In my opinion this is a bug in this library. My suggestion is to make URL
equality the default and even deprecate the whole option to switch to
string equality. (Although, some web servers ignore case of the URL path,
so some users might want **case insensitive** string comparison. But that
is not even an option now.)

Op do 3 feb. 2022 21:30 schreef Dominick Baier ***@***.***>:

**Comment by leastprivilege** [comment]
that would be a breaking change and I never heard anyone else having issues with that.
