### ISSUE TITLE
Created Sample?

### ISSUE THREAD

**Issue by jt4000** [IdentityModel/IdentityModel#446]
Hello,

WHen I have read this article "https://medium.com/@woeterman_94/how-to-automatically-fetch-access-tokens-for-an-http-client-in-net-1fe617545c7c"

Is there a completed sample that I can download via Github and test this instead of creating everything from scratch?

Thank you!

**Comment by leastprivilege** [comment]
see here
https://github.com/IdentityModel/IdentityModel.AspNetCore/tree/main/samples

**Comment by jt4000** [comment]
I have opened the solution in VS 2019 and I tried executing multiple startup project and still it does not work.
What settings do I need to do in order debug the solution?

Thank you!
