### ISSUE TITLE
HttpClientDeviceFlowExtensions.RequestDeviceAuthorizationAsync only emits "scope" parameter

### ISSUE THREAD

**Issue by jelledruyts** [IdentityModel/IdentityModel#454]
This seems to be a regression from v5.2.0 which works fine, but if I use v6 to generate the device code authorization flow, I'm getting an error from the STS saying the client_id is missing. It only sends the "scope" in fact: https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Extensions/HttpClientDeviceFlowExtensions.cs#L28.

**Comment by leastprivilege** [comment]
Starting with v6 we default to sending client creds on the authZ header. You can change this on the request object (ClientCredentialStyle or similar).

**Comment by jelledruyts** [comment]
@leastprivilege my apologies, totally missed that! Indeed, I added the style parameter and all is good with the world again :-)
