### ISSUE TITLE
httpClient.GetDiscoveryDocumentAsync  issue "Endpoint belongs to different authority"

### ISSUE THREAD

**Issue by j0203122** [IdentityModel/IdentityModel#456]
I use IdentityModel 5.2.0 to connect OAuth Server (MicreoFocus Access Managr 5.oFocus Access Manag0.1.2), 

I use httpClient.GetDiscoveryDocumentAsync  to discover OAuth server, but an error occurs : "Endpoint belongs to different authority"  。

After trace IdentityModel source code , it seems to Validate Endpoints , include "allowed Authorities" ,  compare all endpoints URL MUST  start with Issuer's URL,

ex :

Issuer URL  -> https://tw.mx.com/nidp/oauth/nam

endpoint URL meeds to start with Issuer's URL, as :

Token EndPoint URL -> https://tw.mx.com/nidp/oauth/nam/token
UserInfo EndPoint URL -> https://tw.mx.com/nidp/oauth/nam/serinfo

But my OAuth Server (MicroFocus Access Manager 5.0.1.2) has some endpoints URL as https://tw.mx.com/nidp/oauth/v1/nam/end_session

I have some questions about this issue :
(1)Why IdentityModel do such a rule check? Which specification is it based on, OAuth2 RFC 6749 or OpenID?
(2)Any suggetion for this issue ?

**Comment by leastprivilege** [comment]
1) to protect against tampered disco docs
2) you can turn this check off on the policy

**Comment by j0203122** [comment]
Hi Dominick ,
thanks for your feedback.
What does "to protect against tampered disco docs" mean?
thanks !

**Comment by ariveron** [comment]
Let's say you used authority `host-good:443` to make the HTTP request to the discovery endpoint. If a bad actor was somehow able to compromise the discovery document and change the endpoints in the response to use a different authority `host-bad:443`, they may be able to compromise your applications' security. Imagine if they change the `introspection` or `userinfo` endpoint authority to `host-bad:443`, and then you unwittingly send `host-bad:443` an access token when trying to make a call to these endpoints.

**Comment by leastprivilege** [comment]
sorry I missed that. Yes - it's a defense in depth measure.
