### ISSUE TITLE
Claims data not being passed to the Claims based token in .Net 6

### ISSUE THREAD

**Issue by mmadsenxyz** [IdentityModel/IdentityModel#458]
**Claims data is not being passed to the Claims based token in .Net 6**
So its not logging me in since I'm lacking First Name and Last Name data.
**Using:**
.Net 6
IdentityServer4.Models
IdentityServer4.Validation

**Code:**
```
context.Result = new GrantValidationResult(
return Task.CompletedTask;

return new JsonResult(from c in User.Claims select new { c.Type, c.Value });

public class IdentityResult : WebApiResult<List<IdentityClaim>> {
return Result.FirstOrDefault(x => x.Type.Equals("first_name")).Value;
```
**Object reference not set to an instance of the object (Missing First Name and Last Name)**

**Comment by leastprivilege** [comment]
This seems to be the wrong repo.

Also:

> Using:
.Net 6
IdentityServer4.Models
IdentityServer4.Validation

IdentityServer4 does not support .NET 6

**Comment by mmadsenxyz** [comment]
Thank you. I'll have to choose another identity package. Can you recommend something else?

**Comment by leastprivilege** [comment]
https://github.com/DuendeSoftware/IdentityServer
