### ISSUE TITLE
.NET 6.0 support

### ISSUE THREAD

**Issue by GMillerVarian** [IdentityModel/IdentityModel#462]
Is .NET 6.0 tested / supported?

When we upgraded our service from .NET Core 3.1 to .NET 6.0, we noticed cpu / memory resources are much higher (up to 4X or more). When we profiled, we noticed IdentityModel seems to be implicated:

![image](https://user-images.githubusercontent.com/16961923/178036526-40af8fec-d855-4443-8568-8994eb7907e6.png)

**Comment by leastprivilege** [comment]
IdentityModel is a FOSS project - a such, support does not exist - apart from the community helping each other.

That being said - yes, there is a NET6 taget for all the tests and they pass. If you think you have found an issue, please investigate this further so we can hopefully fix it.

Thanks!

**Comment by GMillerVarian** [comment]
This is actually an issue with the "Microsoft.IdentityModel.Tokens" package, which is not "IdentityModel".

For posterity, the fix was including an explicit reference to "System.IdentityModel.Tokens.Jwt", which in turn forced the latest version of "Microsoft.IdentityModel.Tokens" which resolved the issue.

Sorry for posting in the wrong forum!
