### ISSUE TITLE
RequestDeviceAuthorizationAsync fails when both ClientCredentialStyle not set & no Parameters are set

### ISSUE THREAD

**Issue by lemonlion** [IdentityModel/IdentityModel#470]
**Note**:  Originally posted as an [IdentityServer](https://github.com/DuendeSoftware/Support/issues/201) bug, but it would appear to be an IdentityModel issue.

**Which version of Duende IdentityServer are you using?**
IdentityModel 6.0.0

**Which version of .NET are you using?**
.Net 6

**Describe the bug**
When calling RequestDeviceAuthorizationAsync with just Address and ClientId ([as per the example](https://docs.duendesoftware.com/identityserver/v5/reference/endpoints/device_authorization/)) the request fails with a response of "invalid_request".  If you set the ClientCredentialStyle to AuthorizationHeader, or add any parameters to the Parameters property then the request succeeds.

When debugging through the code, the request appears to be failing [on this line in the DeviceAuthorizationEndpoint class](https://github.com/DuendeSoftware/IdentityServer/blob/f00ce9aa732894698edd4d1a09ebbe47ae990f6e/src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs#L66).  This would appear to be caused by the fact that no content header is added, which in turn is because a new FormUrlEncodedContent [is only created if the parameters collection is not empty](https://github.com/IdentityModel/IdentityModel/blob/2e94543bb365995fa3fc9201c407acb2b9578d61/src/Client/Messages/ProtocolRequest.cs#L195) (which is the case for ClientCredentialStyle.PostBody, but not for ClientCredentialStyle.AuthorizationHeader).

**To Reproduce**

1) Call RequestDeviceAuthorizationAsync with valid address, clientId (& clientSecret if necessary)

```
var startAuthorisationResponse = await client.RequestDeviceAuthorizationAsync(new DeviceAuthorizationRequest
{
    Address = disco.DeviceAuthorizationEndpoint,
    ClientId = ClientId,
});
```
2) Note the `{"error":"invalid_request"}` returned.

**Expected behavior**

A valid response

**Log output/exception with stacktrace**

```
[23:00:10 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DeviceAuthorizationEndpoint for /connect/deviceauthorization

[23:00:10 Warning] Duende.IdentityServer.Endpoints.DeviceAuthorizationEndpoint
Invalid HTTP request for device authorize endpoint

[23:00:10 Error] Duende.IdentityServer.Endpoints.DeviceAuthorizationEndpoint
Device authorization error: invalid_request:invalid_request

[23:00:10 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /connect/deviceauthorization responded 400 in 8.5777 ms
```

**Additional context**

In practise, to get around the problem, we have just changed the ClientCredentialStyle to PostBody.  Is there any particular disadvantage/benefit of using one ClientCredentialStyle over the other?

**Comment by leastprivilege** [comment]
This will be fixed in 6.1. Thanks for reporting.
