### ISSUE TITLE
ProtocolResponse.FromHttpResponseAsync does not treat empty sting as invalid json

### ISSUE THREAD

**Issue by rutgersc** [IdentityModel/IdentityModel#473]
See [example testcase](https://github.com/rutgersc/IdentityModel/commit/f80cbf7ecda33b755c71861bfd518c9bd90402b1)

In the case of a badrequest with an empty body (for example `GetUserInfoAsync`), it seems to throw an InvalidOperationException:
```
Operation is not valid due to the current state of the object.
   at System.Text.Json.JsonElement.CheckValidInstance()
   at System.Text.Json.JsonElement.EnumerateObject()
   at IdentityModel.Client.JsonElementExtensions.ToClaims(JsonElement json, String issuer, String[] excludeKeys)
   at IdentityModel.Client.UserInfoResponse.InitializeAsync(Object initializationData)
```

When looking at the code, it looks like there should be 2 outcomes, if i'm [understanding correctly](https://github.com/IdentityModel/IdentityModel/blob/2e94543bb365995fa3fc9201c407acb2b9578d61/src/Client/Messages/ProtocolResponse.cs#L65):
- either there is a body, so that `response.Json` is set
- or invalid json is sent, in which case the `response` exception is set

However, when the body is empty, neither of these 2 is set, which causes an exception when it tries to get the [list of claims](https://github.com/IdentityModel/IdentityModel/blob/2e94543bb365995fa3fc9201c407acb2b9578d61/src/Client/Extensions/JsonElementExtensions.cs#L29) (via [UserInfoResponse.cs](https://github.com/IdentityModel/IdentityModel/blob/2e94543bb365995fa3fc9201c407acb2b9578d61/src/Client/Messages/UserInfoResponse.cs#L26))

So my guess would be: should it not just treat an empty string as invalid json, and let it throw so it takes the exception path?

**Comment by leastprivilege** [comment]
Hi, 

thanks! Please propose a PR.

**Comment by rutgersc** [comment]
I've added the PR

**Comment by rutgersc** [comment]
Hey there, is it possible to merge this one? Should be a pretty safe change.
