### ISSUE TITLE
RequestClientCredentialsTokenAsync Ignores ClientId and ClientSecret

### ISSUE THREAD

**Issue by xaevik** [IdentityModel/IdentityModel#475]
While implementing the process as described in [Requesting a token using the client_credentials Grant Type](https://identitymodel.readthedocs.io/en/latest/client/token.html#requesting-a-token-using-the-client-credentials-grant-type), we noticed that the properties `ClientId` and `ClientSecret` within `ClientCredentialsTokenRequest` are not being parsed and sent as part of the request.

Investigation into the method shows this is accurate:

https://github.com/IdentityModel/IdentityModel/blob/37f219591241d7be5b6d013266daf214f1508b9f/src/Client/Extensions/HttpClientTokenRequestExtensions.cs#L24-L37

Instead we have to manually pass `client_id` and `client_secret` into a `parameters` object for the call to be successful.

**Comment by leastprivilege** [comment]
see here https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/ProtocolRequest.cs#L148-L169

**Comment by xaevik** [comment]
Ah, we'll adjust our code accordingly. Thanks for pointing it out.
