### ISSUE TITLE
[Android][OIDC v5.1.0] 404 browser not found error while logout

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [IdentityModel/IdentityModel#477]
Hi Team,

I'm using OIDC for my MAUI app to authenticate okta and followed this blog to implement OIDC 5.1.0
https://auth0.com/blog/add-authentication-to-dotnet-maui-apps-with-auth0

Log-in works perfectly fine in Android, but logout opens the browser with a 404 error not found message before it returns the result.
The expected scenario is to log out of the okta once the user taps on the logout button.
Do you have any suggestion, as to why the logout fails and the browser opens with a 404 window?

Please find a sample to replicate this from below GitHub repo.
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/issues/133

**Comment by GnanaPriyaNamasivayam** [comment]
Kindly provide us a update on this issue.

**Comment by leastprivilege** [comment]
wrong repo. please use the OidcClient repo.
