### ISSUE TITLE
[iOS]Login into the app throws unsupported respons from server.

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [IdentityModel/IdentityModel#478]
I tried to login into the MAUI cross-platform app, unsupported server error was thrown only on iOS.
Do you have any suggestion why it happens at the same time when it works fine in Android? 

![image](https://user-images.githubusercontent.com/44390143/197196727-2f1c6e38-62c4-402d-a4c9-0b3fa6724137.png)
For sample and blog reference, PFB bug report:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/issues/133
Note: Please update urlBundle scheme in InfoPlist before deployment to replicate the issue as follows. https://auth0.com/blog/add-authentication-to-dotnet-maui-apps-with-auth0/#Apply-Platform-Specific-Changes

**Comment by GnanaPriyaNamasivayam** [comment]
Any suggestion from your end will be really helpful for us to resolve this issue.

**Comment by leastprivilege** [comment]
wrong repo. please use the OidcClient repo.
