### ISSUE TITLE
Refresh token is null on login with oidc 

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [IdentityModel/IdentityModel#488]
Hi Team, 

I have set these properties 
(Authority, Browser = new WebBrowserAuthenticator(), ClientId , PostLogoutRedirectUri, Policy = new Policy { Discovery = new DiscoveryPolicy { ValidateEndpoints = false } }, RedirectUri , Scope , RefreshDiscoveryDocumentForLogin=true, RefreshDiscoveryOnSignatureFailure=true) 

while initializing MAUI application, here login works perfectly fine. 

Issue I'm facing is after 60m Access Token gets expired and login fails. I tried to use the refresh token, unfortunately its null on login.

I'm new here and looking for a way to get a Refresh Token's value in oidc client. 

Kindly share any suggestions to get my issue resolved.

**Comment by leastprivilege** [comment]
That means that your token service has not returned a refresh token.

**Comment by GnanaPriyaNamasivayam** [comment]
Yes.Thanks for the update.

How can I get them from oidcClient. Can you provide any reference or solution to get a refresh token?

**Comment by leastprivilege** [comment]
No. You need to check your provider documentation how it works.

IdentityServer uses the `offline_access` scope for that.
