### ISSUE TITLE
The following assembly has dependencies on a version of the .NET Framework that is higher than the target and might not load correctly during runtime causing a failure

### ISSUE THREAD

**Issue by davyike** [IdentityModel/IdentityModel#491]
I'm receiving the following warning on several of my projects when building. I've tried to understand what's causing it and done a lot of research, and from [what I gather this can only be fixed within the IdentityModel code](https://stackoverflow.com/questions/52698557/higher-net-framework-version-for-system-net-http-than-project).

```
The following assembly has dependencies on a version of the .NET Framework that is higher than the target and might not load correctly during runtime causing a failure: IdentityModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f. The dependencies are: System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. You should either ensure that the dependent assembly is correct for the target framework, or ensure that the target framework you are addressing is that of the dependent assembly.
```

A comment on the link above;
> If that reference is the result of a third-party nuget package, please inform them that their package is broken for full framework use. They should add that as a reference instead of a package reference if they want to support the full framework.

I'm running .NETFramework v4.8.1, and the above occurs on precompiling the `.cshtml` files with `aspnet_compiler.exe`

Is that fixable? Thanks very much.

**Comment by leastprivilege** [comment]
I don't know. Do you know?

**Comment by davyike** [comment]
Nah, this isn't stuff I'm very familar with. I tried forking the repo and adding net481 as a build target but didn't help.
