### ISSUE TITLE
Cryptographic libraries -- Prefix an extra zero-valued octet to the modulus

### ISSUE THREAD

**Issue by SrikJagz** [IdentityModel/IdentityModel#494]
According to  (https://datatracker.ietf.org/doc/html/rfc7518#section-6.3.1.1) some cryptographic libraries   prefix an extra zero-valued octet to the modulus representations they   return, for instance, returning 257 octets for a 2048-bit key, rather   than 256.  Implementations using such libraries will need to take  care to omit the extra octet from the base64url-encoded  representation.

I have fixed this in JSonWebkey.CS as follows

       **_private string _NString;
        public string N {
            get
            {
                return _NString;
            }
            set
            {

                var modulus = Base64Url.Decode(value);
                if (modulus.Length == 257 && modulus[0] == 0)
                {
                    var newModulus = new byte[256];
                    Array.Copy(modulus, 1, newModulus, 0, 256);
                    _NString = Base64Url.Encode(newModulus);
                }
                else
                    _NString = value;

            }
        }_**

**Comment by leastprivilege** [comment]
..and how is this related to this repo?

**Comment by SrikJagz** [comment]
Hi leastprivilege, 

We are using this IdentityModel library to connect to AWS-Federate authentication Servers for Amazon Client and facing this issue. They are inserting 0 octet for 256 Bit Encrypted data and IdentityModel library is throwing exception even before passing the data to be consumed. 

We had to modify this repo to fix this issue. and constantly updating the library before being included.

I would request to include this fix as there are certain Authorization Servers which are following this additional octet strategy.

Please let me know.

Regards,
Srikanth

**Comment by leastprivilege** [comment]
> We had to modify this repo to fix this issue. and constantly updating the library before being included.

What did you have to update? Can you show me as a PR?

**Comment by SrikJagz** [comment]
https://github.com/IdentityModel/IdentityModel/releases/tag/4.1.0

I believe this issue is there in latest versions as well. 

Regards,
Srikanth

**Comment by leastprivilege** [comment]
Interesting - parts of that was copied from

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs

You should make them aware of the problem. They also have the crypto experts to discuss this.

**Comment by leastprivilege** [comment]
@josephdecock could you research if this is necessary? Or if Microsoft fixed this in Wilson?

**Comment by josephdecock** [comment]
I don't think that we need to do this in IdentityModel. The way I'm understanding the spec, isn't it saying that a crypto library could produce a modulus with an extra octet, but that octet shouldn't be included in the JWK? So, when we're reading a JWK from JSON produced by a spec-compliant implementation, there won't be the extra octet in the JSON. Dealing with non-standard input is probably best done on a case-by-case basis, outside IdentityModel. 

I suppose it is also true that you might be creating an instance of the JsonWebKey class and relying on a crypto library that produces a modulus with the extra octet. But I'm not convinced that handling the extra octet belongs in IdentityModel. IMO it's the responsibility of the caller to provide the correct number of octets.
