### ISSUE TITLE
How can I define the Scheme that the Backchannel uses for Challenge?

### ISSUE THREAD

**Issue by 54mu3l** [IdentityModel/IdentityModel#505]
Hi there!

### Context
Our application uses multiple different authentications for our users (Saml2, Cookie, ...).

But our application also connects to different APIs using a Backchannel HttpClient with OpenID Connect. **The connections to the APIs should be completely separate from the authentications for our users (different scheme).** As they have nothing to do with our users and are run independently by our application.

Therefore, we don't want to define `OpenIdConnectDefaults.AuthenticationScheme` as our DefaultChallengeScheme. Because we have other challenges that use a different scheme (for different authentication-flows).

The backchannel works if we add `sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;`. But then all other authentications stop working.

```csharp
builder.Services.AddAuthentication(sharedOptions =>
{
    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme; // <-- we don't want this line, since we also have other challenges with different schemes
})
```

### Question/Problem
**How can we define the Challenge/Authentication-Scheme that is used by the OpenId Connect Backchannel?**

### Our Code
Our code looks like this:

Program.cs (AddAuthentication):
```csharp
builder.Services.AddAuthentication(sharedOptions =>
{
    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddSaml2(options =>
{
    // ...
})
.AddCookie(options =>
{
    // ...          
})
// ...
// ...
// ...
.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    options.Authority = config.Authority;

    options.Configuration = new OpenIdConnectConfiguration
    {
        TokenEndpoint = config.tokenEndpoint
    };

    options.ClientId = config.ClientId;
    options.ClientSecret = config.ClientSecret;
});
```

Program.cs (Configure Client Access Token):
```csharp
builder.Services.AddClientAccessTokenManagement(options =>
{
    options.DefaultClient.Scheme = OpenIdConnectDefaults.AuthenticationScheme; // <-- this doesn't seem to do anything
    options.DefaultClient.Scope = config.Scope;
})
.ConfigureBackchannelHttpClient()
.AddTransientHttpErrorPolicy(RetryPolicy.CreateRetryPolicy);

builder.Services.AddClientAccessTokenHttpClient("api-source-xyz",
    configureClient: client =>
    {
        client.BaseAddress = new Uri(config.BaseAdress);
    })
.AddPolicyHandler(RetryPolicy.GetDefaultRetryPolicy())
.AddPolicyHandler(RetryPolicy.GetDefaultCircuitBreakerPolicy());
```

SomeMethod.cs (This is how we use the HttpClient):
```csharp
var httpClient = httpClientFactory.CreateClient("api-source-xyz");
// ...
```

I haven't found anything in the docs, that adresses this problem. Is it even possible?
Any help would be greatly appreciated!

Thank you!

**Comment by leastprivilege** [comment]
unrelated to this library

**Comment by 54mu3l** [comment]
> unrelated to this library

is it?
