### ISSUE TITLE
RequestRefreshTokenAsync is not working

### ISSUE THREAD

**Issue by tiewboonhan** [IdentityModel/IdentityModel#527]
This method is working with version v5.2.0 but once i upgrade to higher version, i always got a 401 unauthorized response. My application is a .NET 6 application

return await idpClient.RequestRefreshTokenAsync(
    new RefreshTokenRequest
    {
        Address = _configuration.GetSection("TokenEndpoint").Value,
        ClientId = _configuration.GetSection("ClientId").Value,
        ClientSecret = _configuration.GetSection("ClientSecret").Value,
        RefreshToken = refreshToken
    });

Any idea?

**Comment by leastprivilege** [comment]
You would need the exact reason why your STS has rejected the request. 401 is a bit unspecific.

**Comment by tiewboonhan** [comment]
Manage to figure out, thanks. Just to share.

{"AccessToken":null,"IdentityToken":null,"Scope":null,"IssuedTokenType":null,"TokenType":null,"RefreshToken":null,"ErrorDescription":"Invalid authentication method for accessing this endpoint.".........

Above is the response, and it said "Invalid authentication method for accessing this endpoint.". Therefore i suspect related to how the request being sent.


Fix it with set the ClientCredentialStyle = ClientCredentialStyle.PostBody to the RefreshTokenRequest object. thanks.
