### ISSUE TITLE
Why an Email claim is not unique

### ISSUE THREAD

**Issue by smoms** [IdentityModel/IdentityModel#539]
Hi,

can you please clarify why in the definition of the class [JwtClaimTypes.cs](https://github.com/IdentityModel/IdentityModel/blob/main/src/JwtClaimTypes.cs#L43) q comment states that for claim 'Email' "_The relying party MUST NOT rely upon this value being unique_" ? isn't the email address unique also across IdP providers?

thanks

**Comment by leastprivilege** [comment]
Can you change your email address? e.g. in a corporate context, you get married (or divorced) and your name changes...

**Comment by smoms** [comment]
@leastprivilege  thanks. I see where it comes from then. Ok - yet I believe it is not an absolute truth, depends on the business context. Thanks for clarifiying.
