### ISSUE TITLE
Add constructor to DiscoveryCache to dynamically resolve authority URL

### ISSUE THREAD

**Issue by velocitysystems** [IdentityModel/IdentityModel#549]
Existing constructor does not support passing in a `Func<string>` to resolve the base address/discovery document endpoint. This means if the endpoint URL changes dynamically and we wish to bust the cache, we have to replace the entire object instance as calling `Refresh()` will not work.

New Constructor:
`public DiscoveryCache(Func<string> authorityFunc, Func<HttpMessageInvoker> httpClientFunc, DiscoveryPolicy? policy = null)`

Subsequent calls to `Refresh()` will resolve a discovery document response using `authorityFunc` to resolve the URL.

**Comment by leastprivilege** [comment]
Hi - feel free to propose a PR.

**Comment by velocitysystems** [comment]
Thanks @leastprivilege.
Proposed #550 which also adds additional unit tests for `DiscoveryCache`.

**Comment by velocitysystems** [comment]
@leastprivilege Note this approach only uses a single cache not a cache per URL. Would you like me to further modify the PR to maintain a cache per URL?
