### ISSUE TITLE
RequestauthoizationCodeTokenAsync ContentType of application/json

### ISSUE THREAD

**Issue by demyte** [IdentityModel/IdentityModel#558]
Hi all

A provider I am trying to integrate with expects the content type of the call to their token endpoint to swap the code for a token to have a `content-type` of `application/json`.

I can't seem to find a way of doing this with `RequestauthoizationCodeTokenAsync` as it always uses `application/x-www-form-urlencoded`.

Is there a way to do this?

Thanks :)

**Comment by josephdecock** [comment]
RFC 6749 section 4.1.3 says to use form url-encoded parameters in the request and expect json in the response, which is what identity model does. There isn't a way to override this with non standard behavior.

**Comment by demyte** [comment]
@josephdecock thanks for the response.

Its a 3rd party service I am integrating with so I have no control over their requirements unfortunately.

Was just hoping there was a "just set this flag and you can set the contents content-type" :)

All good, thanks again.
