### ISSUE TITLE
Mirror repo readme to nuget

### ISSUE THREAD

**Issue by thompson-tomo** [IdentityModel/IdentityModel#567]
**Is your feature request related to a problem? Please describe.**
The current package readme is not informative about how to use the package

**Describe the solution you'd like**

The nuget package should be using the same readme as the repo to make it as easy as possible for a user to get started with the package.

**Describe alternatives you've considered**
Accept needing to go to github to get information

**Additional context**
N/a

**Comment by josephdecock** [comment]
The new readme is part of our upcoming version 7, and you can see our previews on nuget.org are using it today: https://www.nuget.org/packages/IdentityModel/7.0.0-preview.4#readme-body-tab.
