### ISSUE TITLE
IsAuthenticated == false after upgrading from 4.0.0 to anything above.

### ISSUE THREAD

**Issue by AndersMalmgren** [IdentityModel/IdentityModel#572]
I'm trying to remove newtonsoft from our Project and that requires 5.0 or above.
After upgrading context.User.Identity!.IsAuthenticated returns false in our custom middleware.

If I downgrade it works again. Thanks

**Comment by josephdecock** [comment]
ClaimsPrincicpals are considered authenticated if you specify an authentication method when you create them. Make sure you're using a constructor overload that includes an authentication method when you create the claims principal.

**Comment by AndersMalmgren** [comment]
> ClaimsPrincicpals are considered authenticated if you specify an authentication method when you create them. Make sure you're using a constructor overload that includes an authentication method when you create the claims principal.

We were using identityserver4.accesstokenvalidation It works now when we moved to none deprecated libraries. Thanks
