### ISSUE TITLE
Provide a helper method to derive a code challenge from a code verifier

### ISSUE THREAD

**Issue by Maia-Everett** [IdentityModel/IdentityModel#574]
Some OAuth 2.0 servers and the [OAuth 2.1](https://oauth.net/2.1/) draft specification require PKCE, but IdentityModel lacks a method to derive an `S256` code challenge from a code verifier, so I have to manually write

```cs
var codeChallenge = Base64Url.Encode(SHA256.HashData(Encoding.UTF8.GetBytes(codeVerifier)));
```

which is not very convenient.

**Comment by leastprivilege** [comment]
Feel free to propose some code in form of a PR if you think this is useful for a wider audience.

**Comment by josephdecock** [comment]
If you're using OIDC, you may also want to take a look at IdentityModel.OidcClient. It has a higher level abstraction for handling the authorize redirect and the client side state needed during an OIDC flow, including the pkce parameters.

**Comment by Maia-Everett** [comment]
Unfortunately, I'm not using OIDC, but rather a custom API on top of OAuth 2.0, so I'm only using IdentityModel for OAuth functionality rather than OIDC.

I'll make a PR. Apparently this functionality [was available](https://leastprivilege.com/2016/02/02/pkce-support-in-identityserver-and-identitymodel/) in an ancient version (IdentityModel 1.5), in the form of the string extension `.ToCodeChallenge()`, but was removed in 2.0.

**Comment by josephdecock** [comment]
Hi! We're in the process of rebranding all the open source work that Brock and Dominick started under the IdentityModel organization. These days, all of that work is being maintained by Duende Software, the company they founded. We're keeping it apache licensed, and Brock and Dom are still involved - the new name is just meant to say that we are supporting IdentityModel, etc, and that it is all designed to work well together. IdentityModel is now Duende.IdentityModel, and it's moving into a [new repo](https://github.com/duendeSoftware/foss). I'm closing this issue in favor https://github.com/DuendeSoftware/foss/issues/44 over there. Contributions are still welcome!
