### ISSUE TITLE
missing client_secret in RequestAuthorizationCodeTokenAsync

### ISSUE THREAD

**Issue by stefan-d-p** [IdentityModel/IdentityModel#578]
Hi,

I have a very weird situation when trying to exchange an authorization code for an access token. I tried multiple Identity Providers (Entra, Spotify, FitBit and KeyCloak). With all those mentioned Identity Providers I can successfully retrieve an access token.

When using the same with LinkedIn registered application, however RequestAuthorizationCodeTokenAsync throws an InvalidRequest exception with an error description of invalid_request:A required parameter "client_secret" is missing.

I checked with Postman to see if something might be wrong with my app registration but here I can successfully retrieve an access token. The only thing that catches my eye is that the LinkedIn secret key contains special characters opposed to the ones I got from the other Identity Providers. Example LinkedIn client_secret: "XXX_XXX.XXXXXXXXXXXXXXX.XXXXXXX="

Clueless.

**Comment by Aha43** [comment]
Could this be a case of client secret / client id delivered as form content (NOT recommended, NOT default I believe) and not as the default (I think) is base 64 encoded in the Authorization header? Happened to me once against a public client credential authority for goverment apis.

**Comment by josephdecock** [comment]
Hi! We're in the process of rebranding all the open source work that Brock and Dominick started under the IdentityModel organization. These days, all of that work is being maintained by Duende Software, the company they founded. We're keeping it apache licensed, and Brock and Dom are still involved - the new name is just meant to say that we are supporting IdentityModel, etc, and that it is all designed to work well together. IdentityModel is now Duende.IdentityModel, and it's moving into a [new repo](https://github.com/duendeSoftware/foss). I'm closing this, but if you are still having trouble, please come over to the new home of IdentityServer and open a new issue.
