### ISSUE TITLE
Method RequestClientCredentialsTokenAsync doesn't work for MTLS token requests

### ISSUE THREAD

**Issue by adrilmorell** [IdentityModel/IdentityModel#581]
I'm using the method RequestClientCredentialsTokenAsync from [HttpClientTokenRequestExtensions](https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Extensions/HttpClientTokenRequestExtensions.cs) for tests, and after updating the library IdentityModel to version 6.2.0 from version 5.0.0 some tests broke because the client_id is not sent. I think the client_id is the problem because I see some log messages indicating that the secret was not found, and class MutualTlsSecretParser doesn't return a ParsedSecret when the body doesn't contain a client_id, preventing MTLS access token request from working.

I have tried a workaround, adding the client_id parameter in a duplicate of the method RequestClientCredentialsTokenAsync, inside a class HttpClientExtensions like this:
```
public static class HttpClientExtensions
{
    /// <summary>
    /// Sends a token request using the client_credentials grant type.
    /// </summary>
    /// <param name="client">The client.</param>
    /// <param name="request">The request.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns></returns>
    public static async Task<TokenResponse> RequestClientCredentialsTokenAsync(this HttpMessageInvoker client, ClientCredentialsTokenRequest request, CancellationToken cancellationToken = default)
    {
        var clone = request.Clone();

        clone.Parameters.AddRequired(OidcConstants.TokenRequest.GrantType, OidcConstants.GrantTypes.ClientCredentials);
        clone.Parameters.AddRequired(OidcConstants.TokenRequest.ClientId, request.ClientId); // Line added
        clone.Parameters.AddOptional(OidcConstants.TokenRequest.Scope, request.Scope);

        foreach (var resource in request.Resource)
        {
            clone.Parameters.AddRequired(OidcConstants.TokenRequest.Resource, resource, allowDuplicates: true);
        }

        return await client.RequestTokenAsync(clone, cancellationToken).ConfigureAwait(false);
    }

// rest of source code
}
```

This solves my problem, but I'm wondering what I might be doing wrong and could improve to avoid the workaround. I'm using the method RequestClientCredentialsTokenAsync in my source code like this:
```
var handler = IdentityServerFixture.CreateSocketsHandler();
var client = new HttpClient(handler);
var logger = NullLogger.Instance;
TokenValidationConfig tokenValidationConfig = new();
List<string> tenantValidationWhitelist = new();
var discoveryDocumentResponse = await client.GetDiscoveryDocumentAsync(_identityServerFixture.Address.ToString());
ClientCredentialsTokenRequest tokenRequest = new()
{
    ClientId = IdentityServerFixture.MachineClientId,
    GrantType = OidcConstants.GrantTypes.ClientCredentials,
    Address = discoveryDocumentResponse.MtlsEndpointAliases.TokenEndpoint,
    Scope = "xxx.eventnotifications",
};
tokenRequest.Headers.Add("X-Client-Cert", WebUtility.UrlEncode(ClientCertPem));
var tokenResponse = await client.RequestClientCredentialsTokenAsync(tokenRequest);

tokenResponse.IsError.ShouldBeFalse();
```

The problem is related to MTLS only because other tests using the /connect/token endpoint continue working as expected after the package upgrade.

Thanks in advance.

**Comment by leastprivilege** [comment]
per the OAuth RFC recommendation, we changed the behavior to send the client ID on the Authorization header by default. You can control this behavior on the token request class.

**Comment by adrilmorell** [comment]
Perfect, thank you so much Dominick.
