### ISSUE TITLE
Set ClientCredentialStyle to Post Body by default

### ISSUE THREAD

**Issue by susan12-web** [IdentityModel/IdentityModel#583]
After .net 8 upgrade ClientCredentialStyle this is set to    /// The client credential style.
    /// </value>
    public ClientCredentialStyle ClientCredentialStyle { get; set; } = ClientCredentialStyle.AuthorizationHeader;
    
    But in .net6 it was 
    
         /// The client credential style.
        /// </value>
        public ClientCredentialStyle ClientCredentialStyle { get; set; } = ClientCredentialStyle.PostBody;
        
        
        If I want to Set ClientCredentialStyle to Post Body by default what needs to be done. 
        
        Could you please advice ?

**Comment by leastprivilege** [comment]
We changed this per RFC 6749 recommendation.

If you want to use PostBody you need to set it per request.
