### ISSUE TITLE
System.Text.Json 8.0.0 reference is omitted on .NET 6

### ISSUE THREAD

**Issue by ericstj** [IdentityModel/IdentityModel#584]
I noticed when reviewing package dependencies of other .NET libraries that your library will expose a reference to System.Text.Json 8.0.0 to netstandard projects, but then it omits that when targeting `net6.0`.

That will cause folks to get a load error if they were counting on your package to bring Json 8.0.  .NET 6.0 only has JSON 6.0.

This is related to changes I'm making to System packages here: https://github.com/dotnet/runtime/pull/106172 where we do a similar thing but are careful not to have these gaps between netstandard2.0 and older .NET versions.

**Comment by josephdecock** [comment]
Hi, thanks for opening this issue. This is really interesting and I'm going to read the linked issue in more detail. We generally try to keep our dependencies as relaxed as possible to avoid dependency conflicts, so my initial take is that maybe we should have depended on System.Text.Json 6.0 in our netstandard builds. Do you see a downside to this approach of being as relaxed as possible in our dependencies?

**Comment by damianh** [comment]
Hi, as per pinned issue we are migrating this project to [Duende.IdentityModel](https://github.com/DuendeSoftware/foss/tree/main/identity-model) and will be winding down this project. In `Duende.IdentityModel` We have dropped support for `net6.0` so I believe this is no longer an issue as net8.0 will have STJ 8.0 thus we're using the same STJ version in all supported scenarios.

Closing the issue, but please comment if you feel we have done something incorrect.
