### ISSUE TITLE
Proof-of-possession authentication method

### ISSUE THREAD

**Issue by linuxchata** [IdentityModel/IdentityModel#586]
Are there any considerations to extend `AuthenticationMethods` with `pop` (Proof-of-possession of a key) authentication method to support passkeys/FIDO2? [Authentication Method Reference Values](https://www.iana.org/assignments/authentication-method-reference-values/authentication-method-reference-values.xhtml).

`pop` Proof-of-possession of a key. Unlike the existing `hwk` and `swk` methods, it is unspecified whether the proof-of-possession key is hardware-secured or software-secured. [Source](https://openid.net/specs/openid-connect-eap-acr-values-1_0-01.html#amrValue)

OKTA [supports](https://developer.okta.com/docs/guides/configure-amr-claims-mapping/main/#supported-amr-values-by-authenticator-type) `pop` for `webauthn`.

**Comment by josephdecock** [comment]
I don't think we need anything to support this apart from defining the constant - @linuxchata is that what you're hoping for?

**Comment by linuxchata** [comment]
Yes, only addition of a new constant is expected, if it makes sense for you

**Comment by josephdecock** [comment]
Okay thanks. PRs are welcome :)
