### ISSUE TITLE
Add support in DiscoveryCache to HttpClients with BaseAddress specified

### ISSUE THREAD

**Issue by Kralizek** [IdentityModel/IdentityModel#599]
In my application, I have a HttpClientFactory configured to point at the authority

```
builder.Services.AddHttpClient("idp", http =>
{
    http.BaseAddress = new Uri("https://idp");
});
```

I want to use that client configuration to request the discovery document from the cache.

Currently all `DiscoveryCache` constructors require the authority as string but it's not required to have a value if the `HttpClient` produced by the delegate has a `BaseAddress`.

The snippet below works, but the `null!` passed as argument really hurts my eyes.
```
builder.Services.AddSingleton<IDiscoveryCache>(sp =>
{
    var policy = new DiscoveryPolicy
    {
       // some policy settings
    };
    
    return new DiscoveryCache(null!, () => sp.GetRequiredService<IHttpClientFactory>().CreateClient("idp"), policy);
});
```

I'm open to work on a PR if there is an agreed-upon solution to work on!

**Comment by josephdecock** [comment]
Hi! We're in the process of rebranding all the open source work that Brock and Dominick started under the IdentityModel organization. These days, all of that work is being maintained by Duende Software, the company they founded. We're keeping it apache licensed, and Brock and Dom are still involved - the new name is just meant to say that we are supporting IdentityModel, etc, and that it is all designed to work well together. IdentityModel is now Duende.IdentityModel, and it's moving into a [new repo](https://github.com/duendeSoftware/foss). I'm going to copy this issue over to the new repo, where a PR would be welcome, after we agree on a solution. My first thought is to have a constructor overload like this: 
```cs
public DiscoveryCache(Func<HttpMessageInvoker> httpClientFunc, DiscoveryPolicy? policy = null)
```
And then `_authority`'s type would change to allow nulls.

The only downside that I see is that it is possible to misuse this API, but we have a runtime check already to ensure that there is a base address, and a helpful error message. We should just make sure to include xmldoc that explains the requirements of the new constructor really clearly.
