### ISSUE TITLE
Upgrade the Version of System.Text.Json to latest

### ISSUE THREAD

**Issue by eden-zhang-avepoint** [IdentityModel/IdentityModel#601]
There are some vulnerabilities issue in System.Text.Json 8.0.0
https://github.com/advisories/GHSA-8g4q-xg66-9fp4

**Comment by josephdecock** [comment]
Hi! We're in the process of rebranding all the open source work that Brock and Dominick started under the IdentityModel organization. These days, all of that work is being maintained by Duende Software, the company they founded. We're keeping it apache licensed, and Brock and Dom are still involved - the new name is just meant to say that we are supporting IdentityModel, etc, and that it is all designed to work well together. IdentityModel is now Duende.IdentityModel, and it's moving into a [new repo](https://github.com/duendeSoftware/foss). Our first release is out today and keeps the API surface unchanged but renames the namespaces to include the Duende. prefix, and notably, [updates the dependency](https://www.nuget.org/packages/Duende.IdentityModel#dependencies-body-tab) on System.Text.Json to 8.0.5. A more formal announcement is coming, as we get all the pieces organized.

**Comment by josephdecock** [comment]
Pinning this, as the vulnerability notice is getting people's attention.
