### ISSUE TITLE
Unable to get access token

### ISSUE THREAD

**Issue by viragneilsoft** [IdentityModel/IdentityModel#603]
I am trying to authorize different services. Few of services are getting authorized successfully and receiving access tokens. But while authoring one of the service using DiscoveryCache, GetAsync() method throwing exception which is not getting tracked and program execution is stopped. Following are line of code written from which second line is responsible for breaking program execution.

var discoveryCache = new DiscoveryCache(authority);
**var discovery = await discoveryCache.GetAsync();**

**Comment by josephdecock** [comment]
We're maintaining IdentityModel as Duende.IdentityModel now in its new home over [here](https://github.com/DuendeSoftware/foss/). Could you please create an issue over there?
